8fixes
Wind-River/meta-device-cloud pull request #26
Opened 2018-04-04 06:28 UTC by robertlinux

2018-04-16 07:39 UTC, robertlinux commented
@butlerpaul Any comments, please ?

2018-04-16 16:24 UTC, element-82 requested changes

2018-04-16 16:24 UTC, element-82 commented on conf/layer.conf
This will break the IDP build which uses the old WRL7 build work flow.  You can bitbake add layer for this.

2018-05-02 02:50 UTC, robertlinux commented
@element-82 , I will fix for your comments and re-send a PULL except this one:
 python-paho-mqtt: remove the recipe 

I do think that we need create a branch for WRL7/8/9/10 rather than make master branch work with all WRLinux releases.

And for master branch, we have to set: 
LAYERSERIES_COMPAT_meta-hdc = "sumo"

Otherwise there would be warnings according to new oe-core changes.

I will drop the mqtt patch in the new PULL

2018-05-02 02:52 UTC, closed without merging