Various fixes (V2)
Wind-River/meta-device-cloud pull request #28
Opened 2018-05-02 02:57 UTC by robertlinux

* V2:
  - Drop the patch:
     python-paho-mqtt: remove the recipe
  - Fix for comments in V1
  - Add:
    layer.conf: add LAYERSERIES_COMPAT

2018-05-17 16:28 UTC, element-82 requested changes
Almost there, just a few small fixes required.

2018-05-29 06:35 UTC, robertlinux commented on docs/README.WRL9.md
> +      $ device_manager.py
Fixed

2018-05-29 06:37 UTC, robertlinux commented on docs/README.WRL9.md
> +                             -c api.devicecloud.windriver.com \
Fixed, I use <host> rather than <cloud url>, as generate_config.py's help says it is <host>

2018-05-29 06:42 UTC, robertlinux commented on docs/README.WRL9.md
> +    --templates=feature/python-device-cloud --layers=meta-device-cloud
It is added to WRLINUX_9_LTS_RCPL0016, I think that you should try it after WRLinux 9 rcpl16 releases.

2018-05-29 07:02 UTC, robertlinux commented
Hi @element-82, I've fixed your comments in the PULL, I think that I don't have to send a V3, just update it in the PULL is OK ? To be clear, the PULL is:
https://github.com/robertlinux/meta-device-cloud.git 7fixes

I've verified that the original has been updated.

2018-05-29 07:02 UTC, robertlinux commented on docs/README.WRL10.md
> +======================
Fixed.

2018-05-29 17:08 UTC, element-82 approved these changes
Looks good.  Thanks for the fixes.

2018-05-29 17:08 UTC, merged